server:
  port: 8090
  servlet:
    context-path: /student
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace


course:
  service:
    url: http://localhost:8091/
    name: CourseFeignClient